# Initial Inspection and Visualisation

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
pd.options.display.float_format = '{:.4f}'.format
plt.style.use('seaborn-whitegrid')

/tmp/ipykernel_125178/3756029144.py:4: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn')

In [4]:
df = pd.read_csv('multi_assets.csv', header=[0, 1], index_col=0, parse_dates=True)
df

Price                     Adj Close                                           \
Ticker                           BA    BTC-USD EURUSD=X      GC=F       ^DJI
Date
2014-10-21 00:00:00+00:00  110.5370   386.4750   1.2795 1251.0000 16614.8105
2014-10-22 00:00:00+00:00  105.6067   383.1580   1.2715 1244.8000 16461.3203
2014-10-23 00:00:00+00:00  106.1111   358.4170   1.2641 1228.5000 16677.9004
2014-10-24 00:00:00+00:00  106.2937   358.3450   1.2654 1231.2000 16805.4102
2014-10-25 00:00:00+00:00       NaN   347.2710      NaN       NaN        NaN
...                             ...        ...      ...       ...        ...
2024-10-16 00:00:00+00:00  154.9000 67612.7188   1.0884 2674.0000 43077.6992
2024-10-17 00:00:00+00:00  155.3100 67399.8359   1.0862 2691.0000 43239.0508
2024-10-18 00:00:00+00:00  155.0000 68418.7891   1.0830 2713.7000 43275.9102
2024-10-19 00:00:00+00:00       NaN 68362.7344      NaN       NaN        NaN
2024-10-20 00:00:00+00:00       NaN 69001.7031      NaN       NaN        NaN

Price                        Close                                           \
Ticker                          BA    BTC-USD EURUSD=X      GC=F       ^DJI
Date
2014-10-21 00:00:00+00:00 127.1200   386.4750   1.2795 1251.0000 16614.8105
2014-10-22 00:00:00+00:00 121.4500   383.1580   1.2715 1244.8000 16461.3203
2014-10-23 00:00:00+00:00 122.0300   358.4170   1.2641 1228.5000 16677.9004
2014-10-24 00:00:00+00:00 122.2400   358.3450   1.2654 1231.2000 16805.4102
2014-10-25 00:00:00+00:00      NaN   347.2710      NaN       NaN        NaN
...                            ...        ...      ...       ...        ...
2024-10-16 00:00:00+00:00 154.9000 67612.7188   1.0884 2674.0000 43077.6992
2024-10-17 00:00:00+00:00 155.3100 67399.8359   1.0862 2691.0000 43239.0508
2024-10-18 00:00:00+00:00 155.0000 68418.7891   1.0830 2713.7000 43275.9102
2024-10-19 00:00:00+00:00      NaN 68362.7344      NaN       NaN        NaN
2024-10-20 00:00:00+00:00      NaN 69001.7031      NaN       NaN        NaN

Price                      ...     Open                                \
Ticker                     ...       BA    BTC-USD EURUSD=X      GC=F
Date                       ...
2014-10-21 00:00:00+00:00  ... 125.2100   382.4210   1.2795 1251.0000
2014-10-22 00:00:00+00:00  ... 127.9900   386.1180   1.2714 1244.8000
2014-10-23 00:00:00+00:00  ... 121.2700   382.9620   1.2645 1228.0000
2014-10-24 00:00:00+00:00  ... 122.2000   358.5910   1.2651 1229.4000
2014-10-25 00:00:00+00:00  ...      NaN   358.6110      NaN       NaN
...                        ...      ...        ...      ...       ...
2024-10-16 00:00:00+00:00  ... 151.9100 67042.4609   1.0884 2674.0000
2024-10-17 00:00:00+00:00  ... 155.0000 67617.0781   1.0862 2677.3999
2024-10-18 00:00:00+00:00  ... 155.8400 67419.1094   1.0830 2713.7000
2024-10-19 00:00:00+00:00  ...      NaN 68418.9766      NaN       NaN
2024-10-20 00:00:00+00:00  ...      NaN 68364.1797      NaN       NaN

Price                                       Volume                        \
Ticker                          ^DJI            BA      BTC-USD EURUSD=X
Date
2014-10-21 00:00:00+00:00 16406.0293  5204500.0000     14188900   0.0000
2014-10-22 00:00:00+00:00 16615.2598 13844400.0000     11641300   0.0000
2014-10-23 00:00:00+00:00 16468.0703  7799700.0000     26456900   0.0000
2014-10-24 00:00:00+00:00 16677.0391  4013300.0000     15585700   0.0000
2014-10-25 00:00:00+00:00        NaN           NaN     18127500      NaN
...                              ...           ...          ...      ...
2024-10-16 00:00:00+00:00 42706.4883  8356200.0000  38195189534   0.0000
2024-10-17 00:00:00+00:00 43119.8086  6291800.0000  32790898511   0.0000
2024-10-18 00:00:00+00:00 43187.1211  6025200.0000  36857165014   0.0000
2024-10-19 00:00:00+00:00        NaN           NaN  14443497908      NaN
2024-10-20 00:00:00+00:00        NaN           NaN  18975847518      NaN

Price
Ticker                       GC=F           ^DJI
Date
2014-10-21 00:00:00+00:00 48.0000 105110000.0000
2014-10-22 00:00:00+00:00  2.0000  92050000.0000
2014-10-23 00:00:00+00:00  2.0000  99420000.0000
2014-10-24 00:00:00+00:00 71.0000  90400000.0000
2014-10-25 00:00:00+00:00     NaN            NaN
...                           ...            ...
2024-10-16 00:00:00+00:00  6.0000 297510000.0000
2024-10-17 00:00:00+00:00 30.0000 267370000.0000
2024-10-18 00:00:00+00:00 30.0000 295500000.0000
2024-10-19 00:00:00+00:00     NaN            NaN
2024-10-20 00:00:00+00:00     NaN            NaN

[3653 rows x 30 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3653 entries, 2014-10-21 00:00:00+00:00 to 2024-10-20 00:00:00+00:00
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Adj Close, BA)        2516 non-null   float64
 1   (Adj Close, BTC-USD)   3653 non-null   float64
 2   (Adj Close, EURUSD=X)  2605 non-null   float64
 3   (Adj Close, GC=F)      2513 non-null   float64
 4   (Adj Close, ^DJI)      2516 non-null   float64
 5   (Close, BA)            2516 non-null   float64
 6   (Close, BTC-USD)       3653 non-null   float64
 7   (Close, EURUSD=X)      2605 non-null   float64
 8   (Close, GC=F)          2513 non-null   float64
 9   (Close, ^DJI)          2516 non-null   float64
 10  (High, BA)             2516 non-null   float64
 11  (High, BTC-USD)        3653 non-null   float64
 12  (High, EURUSD=X)       2605 non-null   float64
 13  (High, GC=F)           2513 non-null   float64
 14  (High, ^DJI)           2516 non-null   float64
 15  (Low, BA)              2516 non-null   float64
 16  (Low, BTC-USD)         3653 non-null   float64
 17  (Low, EURUSD=X)        2605 non-null   float64
 18  (Low, GC=F)            2513 non-null   float64
 19  (Low, ^DJI)            2516 non-null   float64
 20  (Open, BA)             2516 non-null   float64
 21  (Open, BTC-USD)        3653 non-null   float64
 22  (Open, EURUSD=X)       2605 non-null   float64
 23  (Open, GC=F)           2513 non-null   float64
 24  (Open, ^DJI)           2516 non-null   float64
 25  (Volume, BA)           2516 non-null   float64
 26  (Volume, BTC-USD)      3653 non-null   int64
 27  (Volume, EURUSD=X)     2605 non-null   float64
 28  (Volume, GC=F)         2513 non-null   float64
 29  (Volume, ^DJI)         2516 non-null   float64
dtypes: float64(29), int64(1)
memory usage: 884.7 KB

In [6]:
df.loc[:, ("Close", "BA")]

Date
2014-10-21 00:00:00+00:00   127.1200
2014-10-22 00:00:00+00:00   121.4500
2014-10-23 00:00:00+00:00   122.0300
2014-10-24 00:00:00+00:00   122.2400
2014-10-25 00:00:00+00:00        NaN
                              ...
2024-10-16 00:00:00+00:00   154.9000
2024-10-17 00:00:00+00:00   155.3100
2024-10-18 00:00:00+00:00   155.0000
2024-10-19 00:00:00+00:00        NaN
2024-10-20 00:00:00+00:00        NaN
Name: (Close, BA), Length: 3653, dtype: float64